### ISSUE TITLE
(number) should reflect total number of items in media library

### ISSUE THREAD

**Issue by andrew-j-s** [collect-nyc/archive#20]
+ whatever units represent some kind of counting up
<img width="1524" alt="Screen Shot 2021-07-26 at 2 38 33 PM" src="https://user-images.githubusercontent.com/78758810/127041427-c388a03c-41a7-4941-8f14-471c91dced5c.png">
 the code

**Comment by joshuatuscan** [comment]
This isn't possible with Prismic
